# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: potato_sauce/proto/geom.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'potato_sauce/proto/geom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpotato_sauce/proto/geom.proto\x12\x11potato_sauce.geom\"!\n\tGridCoord\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"p\n\nGridtangle\x12\x31\n\x0b\x62ottom_left\x18\x01 \x01(\x0b\x32\x1c.potato_sauce.geom.GridCoord\x12/\n\ttop_right\x18\x02 \x01(\x0b\x32\x1c.potato_sauce.geom.GridCoord*q\n\tDirection\x12\x15\n\x11\x44IRECTION_UNKNOWN\x10\x00\x12\x10\n\x0c\x44IRECTION_UP\x10\x01\x12\x12\n\x0e\x44IRECTION_DOWN\x10\x02\x12\x12\n\x0e\x44IRECTION_LEFT\x10\x03\x12\x13\n\x0f\x44IRECTION_RIGHT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'potato_sauce.proto.geom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRECTION']._serialized_start=201
  _globals['_DIRECTION']._serialized_end=314
  _globals['_GRIDCOORD']._serialized_start=52
  _globals['_GRIDCOORD']._serialized_end=85
  _globals['_GRIDTANGLE']._serialized_start=87
  _globals['_GRIDTANGLE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
