# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: potato_sauce/proto/mondrian.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'potato_sauce/proto/mondrian.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from potato_sauce.proto import geom_pb2 as potato__sauce_dot_proto_dot_geom__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!potato_sauce/proto/mondrian.proto\x12\x15potato_sauce.mondrian\x1a\x1dpotato_sauce/proto/geom.proto\"\xd2\x01\n\tSceneSpec\x12\x33\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x1d.potato_sauce.geom.Gridtangle\x12\x39\n\ncomponents\x18\x02 \x03(\x0b\x32%.potato_sauce.mondrian.SceneComponent\x12\x10\n\x08scale_by\x18\x03 \x01(\x05\x12\x43\n\x12thin_rect_strategy\x18\x04 \x01(\x0e\x32\'.potato_sauce.mondrian.ThinRectStrategy\"O\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x01(\x05\x12\r\n\x05green\x18\x02 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x03 \x01(\x05\x12\x12\n\x05\x61lpha\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_alpha\"\xbe\x01\n\x0eSceneComponent\x12\x30\n\tlocations\x18\x01 \x03(\x0b\x32\x1d.potato_sauce.geom.Gridtangle\x12\x38\n\x11\x65xclude_locations\x18\x03 \x03(\x0b\x32\x1d.potato_sauce.geom.Gridtangle\x12:\n\rtiling_config\x18\x04 \x01(\x0b\x32#.potato_sauce.mondrian.TilingConfigJ\x04\x08\x02\x10\x03\"\xed\x01\n\x0cTilingConfig\x12\x31\n\x0b\x66ill_colors\x18\x03 \x03(\x0b\x32\x1c.potato_sauce.mondrian.Color\x12\x32\n\x0c\x62order_color\x18\x04 \x01(\x0b\x32\x1c.potato_sauce.mondrian.Color\x12\x1b\n\x13shade_out_of_bounds\x18\x05 \x01(\x08\x12\x12\n\nedge_sizes\x18\x06 \x03(\x05\x12\x45\n\x16\x65\x64ge_size_combinations\x18\x07 \x03(\x0b\x32%.potato_sauce.mondrian.RectTargetSize\"/\n\x0eRectTargetSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05*Z\n\x10ThinRectStrategy\x12\x19\n\x15THIN_RECT_UNSPECIFIED\x10\x00\x12\x15\n\x11THIN_RECT_SUBSUME\x10\x01\x12\x14\n\x10THIN_RECT_IGNORE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'potato_sauce.proto.mondrian_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THINRECTSTRATEGY']._serialized_start=867
  _globals['_THINRECTSTRATEGY']._serialized_end=957
  _globals['_SCENESPEC']._serialized_start=92
  _globals['_SCENESPEC']._serialized_end=302
  _globals['_COLOR']._serialized_start=304
  _globals['_COLOR']._serialized_end=383
  _globals['_SCENECOMPONENT']._serialized_start=386
  _globals['_SCENECOMPONENT']._serialized_end=576
  _globals['_TILINGCONFIG']._serialized_start=579
  _globals['_TILINGCONFIG']._serialized_end=816
  _globals['_RECTTARGETSIZE']._serialized_start=818
  _globals['_RECTTARGETSIZE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
